name: Python app
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to Docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

      - name: Build the Docker image for Fastapi app
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  # Using DockerfileNew
        run: docker build . -t $DOCKER_USER/titanic-api:latest

    # Not necessary to run
    #  - name: Run the Image
    #    run: docker run -d -p 80:8001 diabetes-fastapi
      - name: Push the Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: docker push $DOCKER_USER/titanic-api

      - name: Logout to Docker hub
        run: docker logout
          
