name: Push Image
# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["Python app"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: sudo docker pull $DOCKER_USER/titanic-api:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f titanic-api-container || true
            
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: sudo docker run -it -d -p 80:8001 --name titanic-api-container $DOCKER_USER/titanic-api:latest

      - name: Logout to Docker hub
        run: docker logout
